default: &default
    adapter: sqlite3
    pool: 5
    timeout: 5000

development:
    <<: *default
    database: data.sqlite3

production:
    <<: *default
    adapter: postgresql
    database: data.postgresql
